// <auto-generated />
using System;
using LoboFlix.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoboFlix.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.Marathon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Marathons");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.MarathonMovie", b =>
                {
                    b.Property<Guid>("MarathonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("MarathonId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MarathonMovies");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CastJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ImdbRating")
                        .HasColumnType("REAL");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RottenTomatoesRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesTmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TmdbRating")
                        .HasColumnType("REAL");

                    b.Property<string>("TrailerYoutubeKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("WatchProvidersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TmdbId", "MediaType")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.ScheduleConfig", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DaysOfWeekJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NightDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NightStartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("ScheduleConfigs");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.ScheduleEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MarathonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarathonId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId", "ScheduledDate");

                    b.ToTable("ScheduleEntries");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.UserMovie", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("UserMovies");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.Marathon", b =>
                {
                    b.HasOne("LoboFlix.Api.Data.Entities.User", "User")
                        .WithMany("Marathons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.MarathonMovie", b =>
                {
                    b.HasOne("LoboFlix.Api.Data.Entities.Marathon", "Marathon")
                        .WithMany("Movies")
                        .HasForeignKey("MarathonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoboFlix.Api.Data.Entities.Movie", "Movie")
                        .WithMany("MarathonMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marathon");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.ScheduleConfig", b =>
                {
                    b.HasOne("LoboFlix.Api.Data.Entities.User", "User")
                        .WithOne("ScheduleConfig")
                        .HasForeignKey("LoboFlix.Api.Data.Entities.ScheduleConfig", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.ScheduleEntry", b =>
                {
                    b.HasOne("LoboFlix.Api.Data.Entities.Marathon", "Marathon")
                        .WithMany()
                        .HasForeignKey("MarathonId");

                    b.HasOne("LoboFlix.Api.Data.Entities.Movie", "Movie")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoboFlix.Api.Data.Entities.User", "User")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marathon");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.UserMovie", b =>
                {
                    b.HasOne("LoboFlix.Api.Data.Entities.Movie", "Movie")
                        .WithMany("UserMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoboFlix.Api.Data.Entities.User", "User")
                        .WithMany("Library")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.Marathon", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.Movie", b =>
                {
                    b.Navigation("MarathonMovies");

                    b.Navigation("ScheduleEntries");

                    b.Navigation("UserMovies");
                });

            modelBuilder.Entity("LoboFlix.Api.Data.Entities.User", b =>
                {
                    b.Navigation("Library");

                    b.Navigation("Marathons");

                    b.Navigation("ScheduleConfig");

                    b.Navigation("ScheduleEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
